version: '3'

services:
  desktop:
    build:
      context: .
      dockerfile: Dockerfile
    image: shinchven/virtual-desktop-contained
    container_name: virtual-desktop-contained
    stdin_open: true
    tty: true
    command: "sh -c 'vncserver -localhost no -geometry 1920x1080 -depth 32' && /bin/bash"
    ports:
      - "5901:5901"

